/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.BasicLit;
import org.xtext.example.mydsl.myDsl.FLOAT_LIT;
import org.xtext.example.mydsl.myDsl.IMAGINARY_LIT;
import org.xtext.example.mydsl.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Basic Lit</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.BasicLitImpl#getInt_lit <em>Int lit</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.BasicLitImpl#getFloat_lit <em>Float lit</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.BasicLitImpl#getImaginary_lit <em>Imaginary lit</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.BasicLitImpl#getRune_lit <em>Rune lit</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.BasicLitImpl#getString_lit <em>String lit</em>}</li>
 * </ul>
 *
 * @generated
 */
public class BasicLitImpl extends MinimalEObjectImpl.Container implements BasicLit
{
  /**
   * The default value of the '{@link #getInt_lit() <em>Int lit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInt_lit()
   * @generated
   * @ordered
   */
  protected static final String INT_LIT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getInt_lit() <em>Int lit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInt_lit()
   * @generated
   * @ordered
   */
  protected String int_lit = INT_LIT_EDEFAULT;

  /**
   * The cached value of the '{@link #getFloat_lit() <em>Float lit</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFloat_lit()
   * @generated
   * @ordered
   */
  protected FLOAT_LIT float_lit;

  /**
   * The cached value of the '{@link #getImaginary_lit() <em>Imaginary lit</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImaginary_lit()
   * @generated
   * @ordered
   */
  protected IMAGINARY_LIT imaginary_lit;

  /**
   * The default value of the '{@link #getRune_lit() <em>Rune lit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRune_lit()
   * @generated
   * @ordered
   */
  protected static final String RUNE_LIT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRune_lit() <em>Rune lit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRune_lit()
   * @generated
   * @ordered
   */
  protected String rune_lit = RUNE_LIT_EDEFAULT;

  /**
   * The default value of the '{@link #getString_lit() <em>String lit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getString_lit()
   * @generated
   * @ordered
   */
  protected static final String STRING_LIT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getString_lit() <em>String lit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getString_lit()
   * @generated
   * @ordered
   */
  protected String string_lit = STRING_LIT_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BasicLitImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.BASIC_LIT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getInt_lit()
  {
    return int_lit;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setInt_lit(String newInt_lit)
  {
    String oldInt_lit = int_lit;
    int_lit = newInt_lit;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.BASIC_LIT__INT_LIT, oldInt_lit, int_lit));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FLOAT_LIT getFloat_lit()
  {
    return float_lit;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFloat_lit(FLOAT_LIT newFloat_lit, NotificationChain msgs)
  {
    FLOAT_LIT oldFloat_lit = float_lit;
    float_lit = newFloat_lit;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.BASIC_LIT__FLOAT_LIT, oldFloat_lit, newFloat_lit);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFloat_lit(FLOAT_LIT newFloat_lit)
  {
    if (newFloat_lit != float_lit)
    {
      NotificationChain msgs = null;
      if (float_lit != null)
        msgs = ((InternalEObject)float_lit).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.BASIC_LIT__FLOAT_LIT, null, msgs);
      if (newFloat_lit != null)
        msgs = ((InternalEObject)newFloat_lit).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.BASIC_LIT__FLOAT_LIT, null, msgs);
      msgs = basicSetFloat_lit(newFloat_lit, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.BASIC_LIT__FLOAT_LIT, newFloat_lit, newFloat_lit));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IMAGINARY_LIT getImaginary_lit()
  {
    return imaginary_lit;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetImaginary_lit(IMAGINARY_LIT newImaginary_lit, NotificationChain msgs)
  {
    IMAGINARY_LIT oldImaginary_lit = imaginary_lit;
    imaginary_lit = newImaginary_lit;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.BASIC_LIT__IMAGINARY_LIT, oldImaginary_lit, newImaginary_lit);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setImaginary_lit(IMAGINARY_LIT newImaginary_lit)
  {
    if (newImaginary_lit != imaginary_lit)
    {
      NotificationChain msgs = null;
      if (imaginary_lit != null)
        msgs = ((InternalEObject)imaginary_lit).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.BASIC_LIT__IMAGINARY_LIT, null, msgs);
      if (newImaginary_lit != null)
        msgs = ((InternalEObject)newImaginary_lit).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.BASIC_LIT__IMAGINARY_LIT, null, msgs);
      msgs = basicSetImaginary_lit(newImaginary_lit, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.BASIC_LIT__IMAGINARY_LIT, newImaginary_lit, newImaginary_lit));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getRune_lit()
  {
    return rune_lit;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setRune_lit(String newRune_lit)
  {
    String oldRune_lit = rune_lit;
    rune_lit = newRune_lit;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.BASIC_LIT__RUNE_LIT, oldRune_lit, rune_lit));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getString_lit()
  {
    return string_lit;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setString_lit(String newString_lit)
  {
    String oldString_lit = string_lit;
    string_lit = newString_lit;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.BASIC_LIT__STRING_LIT, oldString_lit, string_lit));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.BASIC_LIT__FLOAT_LIT:
        return basicSetFloat_lit(null, msgs);
      case MyDslPackage.BASIC_LIT__IMAGINARY_LIT:
        return basicSetImaginary_lit(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.BASIC_LIT__INT_LIT:
        return getInt_lit();
      case MyDslPackage.BASIC_LIT__FLOAT_LIT:
        return getFloat_lit();
      case MyDslPackage.BASIC_LIT__IMAGINARY_LIT:
        return getImaginary_lit();
      case MyDslPackage.BASIC_LIT__RUNE_LIT:
        return getRune_lit();
      case MyDslPackage.BASIC_LIT__STRING_LIT:
        return getString_lit();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.BASIC_LIT__INT_LIT:
        setInt_lit((String)newValue);
        return;
      case MyDslPackage.BASIC_LIT__FLOAT_LIT:
        setFloat_lit((FLOAT_LIT)newValue);
        return;
      case MyDslPackage.BASIC_LIT__IMAGINARY_LIT:
        setImaginary_lit((IMAGINARY_LIT)newValue);
        return;
      case MyDslPackage.BASIC_LIT__RUNE_LIT:
        setRune_lit((String)newValue);
        return;
      case MyDslPackage.BASIC_LIT__STRING_LIT:
        setString_lit((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.BASIC_LIT__INT_LIT:
        setInt_lit(INT_LIT_EDEFAULT);
        return;
      case MyDslPackage.BASIC_LIT__FLOAT_LIT:
        setFloat_lit((FLOAT_LIT)null);
        return;
      case MyDslPackage.BASIC_LIT__IMAGINARY_LIT:
        setImaginary_lit((IMAGINARY_LIT)null);
        return;
      case MyDslPackage.BASIC_LIT__RUNE_LIT:
        setRune_lit(RUNE_LIT_EDEFAULT);
        return;
      case MyDslPackage.BASIC_LIT__STRING_LIT:
        setString_lit(STRING_LIT_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.BASIC_LIT__INT_LIT:
        return INT_LIT_EDEFAULT == null ? int_lit != null : !INT_LIT_EDEFAULT.equals(int_lit);
      case MyDslPackage.BASIC_LIT__FLOAT_LIT:
        return float_lit != null;
      case MyDslPackage.BASIC_LIT__IMAGINARY_LIT:
        return imaginary_lit != null;
      case MyDslPackage.BASIC_LIT__RUNE_LIT:
        return RUNE_LIT_EDEFAULT == null ? rune_lit != null : !RUNE_LIT_EDEFAULT.equals(rune_lit);
      case MyDslPackage.BASIC_LIT__STRING_LIT:
        return STRING_LIT_EDEFAULT == null ? string_lit != null : !STRING_LIT_EDEFAULT.equals(string_lit);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (int_lit: ");
    result.append(int_lit);
    result.append(", rune_lit: ");
    result.append(rune_lit);
    result.append(", string_lit: ");
    result.append(string_lit);
    result.append(')');
    return result.toString();
  }

} //BasicLitImpl
