/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.ChannelTypeLinha;
import org.xtext.example.mydsl.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Channel Type Linha</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ChannelTypeLinhaImpl#getANY_OTHER <em>ANY OTHER</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ChannelTypeLinhaImpl extends MinimalEObjectImpl.Container implements ChannelTypeLinha
{
  /**
   * The default value of the '{@link #getANY_OTHER() <em>ANY OTHER</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getANY_OTHER()
   * @generated
   * @ordered
   */
  protected static final String ANY_OTHER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getANY_OTHER() <em>ANY OTHER</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getANY_OTHER()
   * @generated
   * @ordered
   */
  protected String aNY_OTHER = ANY_OTHER_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ChannelTypeLinhaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.CHANNEL_TYPE_LINHA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getANY_OTHER()
  {
    return aNY_OTHER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setANY_OTHER(String newANY_OTHER)
  {
    String oldANY_OTHER = aNY_OTHER;
    aNY_OTHER = newANY_OTHER;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.CHANNEL_TYPE_LINHA__ANY_OTHER, oldANY_OTHER, aNY_OTHER));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.CHANNEL_TYPE_LINHA__ANY_OTHER:
        return getANY_OTHER();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.CHANNEL_TYPE_LINHA__ANY_OTHER:
        setANY_OTHER((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.CHANNEL_TYPE_LINHA__ANY_OTHER:
        setANY_OTHER(ANY_OTHER_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.CHANNEL_TYPE_LINHA__ANY_OTHER:
        return ANY_OTHER_EDEFAULT == null ? aNY_OTHER != null : !ANY_OTHER_EDEFAULT.equals(aNY_OTHER);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (aNY_OTHER: ");
    result.append(aNY_OTHER);
    result.append(')');
    return result.toString();
  }

} //ChannelTypeLinhaImpl
