/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Block</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Block#getStatementList <em>Statement List</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getBlock()
 * @model
 * @generated
 */
public interface Block extends EObject
{
  /**
   * Returns the value of the '<em><b>Statement List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Statement List</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statement List</em>' containment reference.
   * @see #setStatementList(StatementList)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getBlock_StatementList()
   * @model containment="true"
   * @generated
   */
  StatementList getStatementList();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Block#getStatementList <em>Statement List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Statement List</em>' containment reference.
   * @see #getStatementList()
   * @generated
   */
  void setStatementList(StatementList value);

} // Block
