/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Empty Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.EmptyStmt#getANY_OTHER <em>ANY OTHER</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getEmptyStmt()
 * @model
 * @generated
 */
public interface EmptyStmt extends EObject
{
  /**
   * Returns the value of the '<em><b>ANY OTHER</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>ANY OTHER</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>ANY OTHER</em>' attribute.
   * @see #setANY_OTHER(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getEmptyStmt_ANY_OTHER()
   * @model
   * @generated
   */
  String getANY_OTHER();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.EmptyStmt#getANY_OTHER <em>ANY OTHER</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>ANY OTHER</em>' attribute.
   * @see #getANY_OTHER()
   * @generated
   */
  void setANY_OTHER(String value);

} // EmptyStmt
