/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr Switch Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ExprSwitchStmt#getSwitch <em>Switch</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ExprSwitchStmt#getSimpleStmt <em>Simple Stmt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ExprSwitchStmt#getExpression <em>Expression</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ExprSwitchStmt#getExprCaseClause <em>Expr Case Clause</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getExprSwitchStmt()
 * @model
 * @generated
 */
public interface ExprSwitchStmt extends EObject
{
  /**
   * Returns the value of the '<em><b>Switch</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Switch</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Switch</em>' attribute.
   * @see #setSwitch(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getExprSwitchStmt_Switch()
   * @model
   * @generated
   */
  String getSwitch();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ExprSwitchStmt#getSwitch <em>Switch</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Switch</em>' attribute.
   * @see #getSwitch()
   * @generated
   */
  void setSwitch(String value);

  /**
   * Returns the value of the '<em><b>Simple Stmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Simple Stmt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Simple Stmt</em>' containment reference.
   * @see #setSimpleStmt(SimpleStmt)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getExprSwitchStmt_SimpleStmt()
   * @model containment="true"
   * @generated
   */
  SimpleStmt getSimpleStmt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ExprSwitchStmt#getSimpleStmt <em>Simple Stmt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Simple Stmt</em>' containment reference.
   * @see #getSimpleStmt()
   * @generated
   */
  void setSimpleStmt(SimpleStmt value);

  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(Expression)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getExprSwitchStmt_Expression()
   * @model containment="true"
   * @generated
   */
  Expression getExpression();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ExprSwitchStmt#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(Expression value);

  /**
   * Returns the value of the '<em><b>Expr Case Clause</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.ExprCaseClause}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr Case Clause</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr Case Clause</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getExprSwitchStmt_ExprCaseClause()
   * @model containment="true"
   * @generated
   */
  EList<ExprCaseClause> getExprCaseClause();

} // ExprSwitchStmt
