/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression Linha</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Expression_Linha#getBINARY_OP <em>BINARY OP</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Expression_Linha#getExpression1 <em>Expression1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Expression_Linha#getExpression_Linha <em>Expression Linha</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getExpression_Linha()
 * @model
 * @generated
 */
public interface Expression_Linha extends EObject
{
  /**
   * Returns the value of the '<em><b>BINARY OP</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>BINARY OP</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>BINARY OP</em>' containment reference.
   * @see #setBINARY_OP(BINARY_OP)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getExpression_Linha_BINARY_OP()
   * @model containment="true"
   * @generated
   */
  BINARY_OP getBINARY_OP();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Expression_Linha#getBINARY_OP <em>BINARY OP</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>BINARY OP</em>' containment reference.
   * @see #getBINARY_OP()
   * @generated
   */
  void setBINARY_OP(BINARY_OP value);

  /**
   * Returns the value of the '<em><b>Expression1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expression1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression1</em>' containment reference.
   * @see #setExpression1(Expression1)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getExpression_Linha_Expression1()
   * @model containment="true"
   * @generated
   */
  Expression1 getExpression1();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Expression_Linha#getExpression1 <em>Expression1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression1</em>' containment reference.
   * @see #getExpression1()
   * @generated
   */
  void setExpression1(Expression1 value);

  /**
   * Returns the value of the '<em><b>Expression Linha</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expression Linha</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression Linha</em>' containment reference.
   * @see #setExpression_Linha(Expression_Linha)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getExpression_Linha_Expression_Linha()
   * @model containment="true"
   * @generated
   */
  Expression_Linha getExpression_Linha();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Expression_Linha#getExpression_Linha <em>Expression Linha</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression Linha</em>' containment reference.
   * @see #getExpression_Linha()
   * @generated
   */
  void setExpression_Linha(Expression_Linha value);

} // Expression_Linha
