/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fallthrough Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.FallthroughStmt#getFallthrough <em>Fallthrough</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFallthroughStmt()
 * @model
 * @generated
 */
public interface FallthroughStmt extends EObject
{
  /**
   * Returns the value of the '<em><b>Fallthrough</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fallthrough</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fallthrough</em>' attribute.
   * @see #setFallthrough(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFallthroughStmt_Fallthrough()
   * @model
   * @generated
   */
  String getFallthrough();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.FallthroughStmt#getFallthrough <em>Fallthrough</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fallthrough</em>' attribute.
   * @see #getFallthrough()
   * @generated
   */
  void setFallthrough(String value);

} // FallthroughStmt
