/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>If Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.IfStmt#getIf <em>If</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.IfStmt#getExpression <em>Expression</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.IfStmt#getIfStmtLinha <em>If Stmt Linha</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.IfStmt#getEmptyStmt <em>Empty Stmt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.IfStmt#getShortVarDecl <em>Short Var Decl</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.IfStmt#getBlock <em>Block</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.IfStmt#getElse <em>Else</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.IfStmt#getIfStmt <em>If Stmt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.IfStmt#getBlock1 <em>Block1</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getIfStmt()
 * @model
 * @generated
 */
public interface IfStmt extends EObject
{
  /**
   * Returns the value of the '<em><b>If</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>If</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>If</em>' attribute.
   * @see #setIf(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getIfStmt_If()
   * @model
   * @generated
   */
  String getIf();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.IfStmt#getIf <em>If</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>If</em>' attribute.
   * @see #getIf()
   * @generated
   */
  void setIf(String value);

  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(Expression)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getIfStmt_Expression()
   * @model containment="true"
   * @generated
   */
  Expression getExpression();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.IfStmt#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(Expression value);

  /**
   * Returns the value of the '<em><b>If Stmt Linha</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>If Stmt Linha</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>If Stmt Linha</em>' containment reference.
   * @see #setIfStmtLinha(IfStmtLinha)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getIfStmt_IfStmtLinha()
   * @model containment="true"
   * @generated
   */
  IfStmtLinha getIfStmtLinha();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.IfStmt#getIfStmtLinha <em>If Stmt Linha</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>If Stmt Linha</em>' containment reference.
   * @see #getIfStmtLinha()
   * @generated
   */
  void setIfStmtLinha(IfStmtLinha value);

  /**
   * Returns the value of the '<em><b>Empty Stmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Empty Stmt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Empty Stmt</em>' containment reference.
   * @see #setEmptyStmt(EmptyStmt)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getIfStmt_EmptyStmt()
   * @model containment="true"
   * @generated
   */
  EmptyStmt getEmptyStmt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.IfStmt#getEmptyStmt <em>Empty Stmt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Empty Stmt</em>' containment reference.
   * @see #getEmptyStmt()
   * @generated
   */
  void setEmptyStmt(EmptyStmt value);

  /**
   * Returns the value of the '<em><b>Short Var Decl</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Short Var Decl</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Short Var Decl</em>' containment reference.
   * @see #setShortVarDecl(ShortVarDecl)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getIfStmt_ShortVarDecl()
   * @model containment="true"
   * @generated
   */
  ShortVarDecl getShortVarDecl();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.IfStmt#getShortVarDecl <em>Short Var Decl</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Short Var Decl</em>' containment reference.
   * @see #getShortVarDecl()
   * @generated
   */
  void setShortVarDecl(ShortVarDecl value);

  /**
   * Returns the value of the '<em><b>Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Block</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Block</em>' containment reference.
   * @see #setBlock(Block)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getIfStmt_Block()
   * @model containment="true"
   * @generated
   */
  Block getBlock();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.IfStmt#getBlock <em>Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Block</em>' containment reference.
   * @see #getBlock()
   * @generated
   */
  void setBlock(Block value);

  /**
   * Returns the value of the '<em><b>Else</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Else</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Else</em>' attribute.
   * @see #setElse(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getIfStmt_Else()
   * @model
   * @generated
   */
  String getElse();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.IfStmt#getElse <em>Else</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Else</em>' attribute.
   * @see #getElse()
   * @generated
   */
  void setElse(String value);

  /**
   * Returns the value of the '<em><b>If Stmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>If Stmt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>If Stmt</em>' containment reference.
   * @see #setIfStmt(IfStmt)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getIfStmt_IfStmt()
   * @model containment="true"
   * @generated
   */
  IfStmt getIfStmt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.IfStmt#getIfStmt <em>If Stmt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>If Stmt</em>' containment reference.
   * @see #getIfStmt()
   * @generated
   */
  void setIfStmt(IfStmt value);

  /**
   * Returns the value of the '<em><b>Block1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Block1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Block1</em>' containment reference.
   * @see #setBlock1(Block)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getIfStmt_Block1()
   * @model containment="true"
   * @generated
   */
  Block getBlock1();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.IfStmt#getBlock1 <em>Block1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Block1</em>' containment reference.
   * @see #getBlock1()
   * @generated
   */
  void setBlock1(Block value);

} // IfStmt
