/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Primary Expr Linha</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.PrimaryExprLinha#getSelector <em>Selector</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.PrimaryExprLinha#getPrimaryExprLinha <em>Primary Expr Linha</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.PrimaryExprLinha#getIndex <em>Index</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.PrimaryExprLinha#getSlice <em>Slice</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.PrimaryExprLinha#getTypeAssertion <em>Type Assertion</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.PrimaryExprLinha#getArguments <em>Arguments</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPrimaryExprLinha()
 * @model
 * @generated
 */
public interface PrimaryExprLinha extends EObject
{
  /**
   * Returns the value of the '<em><b>Selector</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Selector</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Selector</em>' containment reference.
   * @see #setSelector(Selector)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPrimaryExprLinha_Selector()
   * @model containment="true"
   * @generated
   */
  Selector getSelector();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.PrimaryExprLinha#getSelector <em>Selector</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Selector</em>' containment reference.
   * @see #getSelector()
   * @generated
   */
  void setSelector(Selector value);

  /**
   * Returns the value of the '<em><b>Primary Expr Linha</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Primary Expr Linha</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Primary Expr Linha</em>' containment reference.
   * @see #setPrimaryExprLinha(PrimaryExprLinha)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPrimaryExprLinha_PrimaryExprLinha()
   * @model containment="true"
   * @generated
   */
  PrimaryExprLinha getPrimaryExprLinha();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.PrimaryExprLinha#getPrimaryExprLinha <em>Primary Expr Linha</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Primary Expr Linha</em>' containment reference.
   * @see #getPrimaryExprLinha()
   * @generated
   */
  void setPrimaryExprLinha(PrimaryExprLinha value);

  /**
   * Returns the value of the '<em><b>Index</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Index</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Index</em>' containment reference.
   * @see #setIndex(Index)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPrimaryExprLinha_Index()
   * @model containment="true"
   * @generated
   */
  Index getIndex();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.PrimaryExprLinha#getIndex <em>Index</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Index</em>' containment reference.
   * @see #getIndex()
   * @generated
   */
  void setIndex(Index value);

  /**
   * Returns the value of the '<em><b>Slice</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Slice</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Slice</em>' containment reference.
   * @see #setSlice(Slice)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPrimaryExprLinha_Slice()
   * @model containment="true"
   * @generated
   */
  Slice getSlice();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.PrimaryExprLinha#getSlice <em>Slice</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Slice</em>' containment reference.
   * @see #getSlice()
   * @generated
   */
  void setSlice(Slice value);

  /**
   * Returns the value of the '<em><b>Type Assertion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type Assertion</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Assertion</em>' containment reference.
   * @see #setTypeAssertion(TypeAssertion)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPrimaryExprLinha_TypeAssertion()
   * @model containment="true"
   * @generated
   */
  TypeAssertion getTypeAssertion();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.PrimaryExprLinha#getTypeAssertion <em>Type Assertion</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Assertion</em>' containment reference.
   * @see #getTypeAssertion()
   * @generated
   */
  void setTypeAssertion(TypeAssertion value);

  /**
   * Returns the value of the '<em><b>Arguments</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Arguments</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arguments</em>' containment reference.
   * @see #setArguments(Arguments)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPrimaryExprLinha_Arguments()
   * @model containment="true"
   * @generated
   */
  Arguments getArguments();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.PrimaryExprLinha#getArguments <em>Arguments</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Arguments</em>' containment reference.
   * @see #getArguments()
   * @generated
   */
  void setArguments(Arguments value);

} // PrimaryExprLinha
