/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Switch Stmt Linha</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SwitchStmtLinha#getPrimaryExpr <em>Primary Expr</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SwitchStmtLinha#getSwitchStmtLinhaLinha <em>Switch Stmt Linha Linha</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SwitchStmtLinha#getUnary_op <em>Unary op</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SwitchStmtLinha#getUnaryExpr <em>Unary Expr</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SwitchStmtLinha#getExpression <em>Expression</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SwitchStmtLinha#getExprCaseClause <em>Expr Case Clause</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SwitchStmtLinha#getId <em>Id</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SwitchStmtLinha#getTypekeyword <em>Typekeyword</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SwitchStmtLinha#getTypeCaseClause <em>Type Case Clause</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSwitchStmtLinha()
 * @model
 * @generated
 */
public interface SwitchStmtLinha extends EObject
{
  /**
   * Returns the value of the '<em><b>Primary Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Primary Expr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Primary Expr</em>' containment reference.
   * @see #setPrimaryExpr(PrimaryExpr)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSwitchStmtLinha_PrimaryExpr()
   * @model containment="true"
   * @generated
   */
  PrimaryExpr getPrimaryExpr();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.SwitchStmtLinha#getPrimaryExpr <em>Primary Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Primary Expr</em>' containment reference.
   * @see #getPrimaryExpr()
   * @generated
   */
  void setPrimaryExpr(PrimaryExpr value);

  /**
   * Returns the value of the '<em><b>Switch Stmt Linha Linha</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Switch Stmt Linha Linha</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Switch Stmt Linha Linha</em>' containment reference.
   * @see #setSwitchStmtLinhaLinha(SwitchStmtLinhaLinha)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSwitchStmtLinha_SwitchStmtLinhaLinha()
   * @model containment="true"
   * @generated
   */
  SwitchStmtLinhaLinha getSwitchStmtLinhaLinha();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.SwitchStmtLinha#getSwitchStmtLinhaLinha <em>Switch Stmt Linha Linha</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Switch Stmt Linha Linha</em>' containment reference.
   * @see #getSwitchStmtLinhaLinha()
   * @generated
   */
  void setSwitchStmtLinhaLinha(SwitchStmtLinhaLinha value);

  /**
   * Returns the value of the '<em><b>Unary op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Unary op</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unary op</em>' attribute.
   * @see #setUnary_op(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSwitchStmtLinha_Unary_op()
   * @model
   * @generated
   */
  String getUnary_op();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.SwitchStmtLinha#getUnary_op <em>Unary op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unary op</em>' attribute.
   * @see #getUnary_op()
   * @generated
   */
  void setUnary_op(String value);

  /**
   * Returns the value of the '<em><b>Unary Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Unary Expr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unary Expr</em>' containment reference.
   * @see #setUnaryExpr(UnaryExpr)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSwitchStmtLinha_UnaryExpr()
   * @model containment="true"
   * @generated
   */
  UnaryExpr getUnaryExpr();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.SwitchStmtLinha#getUnaryExpr <em>Unary Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unary Expr</em>' containment reference.
   * @see #getUnaryExpr()
   * @generated
   */
  void setUnaryExpr(UnaryExpr value);

  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(Expression_Linha)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSwitchStmtLinha_Expression()
   * @model containment="true"
   * @generated
   */
  Expression_Linha getExpression();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.SwitchStmtLinha#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(Expression_Linha value);

  /**
   * Returns the value of the '<em><b>Expr Case Clause</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.ExprCaseClause}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr Case Clause</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr Case Clause</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSwitchStmtLinha_ExprCaseClause()
   * @model containment="true"
   * @generated
   */
  EList<ExprCaseClause> getExprCaseClause();

  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Id</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSwitchStmtLinha_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.SwitchStmtLinha#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

  /**
   * Returns the value of the '<em><b>Typekeyword</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Typekeyword</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Typekeyword</em>' attribute.
   * @see #setTypekeyword(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSwitchStmtLinha_Typekeyword()
   * @model
   * @generated
   */
  String getTypekeyword();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.SwitchStmtLinha#getTypekeyword <em>Typekeyword</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Typekeyword</em>' attribute.
   * @see #getTypekeyword()
   * @generated
   */
  void setTypekeyword(String value);

  /**
   * Returns the value of the '<em><b>Type Case Clause</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.TypeCaseClause}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type Case Clause</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Case Clause</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSwitchStmtLinha_TypeCaseClause()
   * @model containment="true"
   * @generated
   */
  EList<TypeCaseClause> getTypeCaseClause();

} // SwitchStmtLinha
