/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Case Clause</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.TypeCaseClause#getTypeSwitchCase <em>Type Switch Case</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.TypeCaseClause#getStatementList <em>Statement List</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTypeCaseClause()
 * @model
 * @generated
 */
public interface TypeCaseClause extends EObject
{
  /**
   * Returns the value of the '<em><b>Type Switch Case</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type Switch Case</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Switch Case</em>' containment reference.
   * @see #setTypeSwitchCase(TypeSwitchCase)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTypeCaseClause_TypeSwitchCase()
   * @model containment="true"
   * @generated
   */
  TypeSwitchCase getTypeSwitchCase();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.TypeCaseClause#getTypeSwitchCase <em>Type Switch Case</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Switch Case</em>' containment reference.
   * @see #getTypeSwitchCase()
   * @generated
   */
  void setTypeSwitchCase(TypeSwitchCase value);

  /**
   * Returns the value of the '<em><b>Statement List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Statement List</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statement List</em>' containment reference.
   * @see #setStatementList(StatementList)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTypeCaseClause_StatementList()
   * @model containment="true"
   * @generated
   */
  StatementList getStatementList();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.TypeCaseClause#getStatementList <em>Statement List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Statement List</em>' containment reference.
   * @see #getStatementList()
   * @generated
   */
  void setStatementList(StatementList value);

} // TypeCaseClause
