/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.validation

import java.util.ArrayList
import java.util.HashMap
import java.util.List
import java.util.Map
import org.eclipse.xtext.validation.Check
import org.xtext.example.mydsl.myDsl.Declaration
import org.xtext.example.mydsl.myDsl.ExprSwitchStmt
import org.xtext.example.mydsl.myDsl.MethodDecl
import org.xtext.example.mydsl.myDsl.MyDslPackage
import org.xtext.example.mydsl.myDsl.SwitchStmt

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class MyDslValidator extends AbstractMyDslValidator {
	
	SwitchValidator switchValidator = new SwitchValidator();
	ConstDeclValidator constDeclValidator = new ConstDeclValidator();
	MethodDeclValidator methodDeclValidator = new MethodDeclValidator();
	VarDeclValidator varDeclValidator = new VarDeclValidator();
	TypeDeclValidator typeDeclValidator = new TypeDeclValidator();
	Map<String, String> idsTypes = new HashMap<String,String>;
	List<MethodDecl> methodDeclList = new ArrayList;
	Map<String, String> typeDefs = new HashMap;
	
//	public static val INVALID_NAME = 'invalidName'
//S
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MyDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}

	//List<PointerType> ponteiros = new ArrayList;
	//List<TypeName> typeName = new ArrayList;
	
	@Check
	def checkMethodDecl(MethodDecl methodDecl){
		if(methodDeclValidator.checkMethodDecl(methodDecl, methodDeclList, typeDefs) != null){
			var String erro = methodDeclValidator.checkMethodDecl(methodDecl, methodDeclList, typeDefs);
			error(erro, MyDslPackage.Literals.METHOD_DECL__RECEIVER);
		}
	}
	
	@Check
	def checkDecl(Declaration decl){
		if(decl.constDecl != null){
			if(constDeclValidator.validaConstDecl(decl.constDecl) != null){
				var String erro = constDeclValidator.validaConstDecl(decl.constDecl)
				error(erro, MyDslPackage.Literals.DECLARATION__CONST_DECL)
			}
		}else if(decl.typeDecl != null){
			typeDeclValidator.addIdsTypes(decl.typeDecl, idsTypes, typeDefs);
		}else{
			if(varDeclValidator.validaVarDecl(decl.varDecl,idsTypes) != null){
				var String erro = varDeclValidator.validaVarDecl(decl.varDecl, idsTypes);
				error(erro, MyDslPackage.Literals.DECLARATION__VAR_DECL)
			}
		}
	}
	
	/*@Check
	def checkExpression(Expression exp){
		if(exp != null){
			
		}
	}*/
	
	@Check
	def checkSwitchStmt(SwitchStmt switchStmt){
		if (switchValidator.validaSwitchStmt(switchStmt) != null){
			var String erro = switchValidator.validaSwitchStmt(switchStmt);
			error(erro, MyDslPackage.Literals.SWITCH_STMT__TYPE_SWITCH_STMT);
		}
	}
	
}
